# dates specifies the test dates for which you want to run the prediction. You can choose multiple dates 
dates: '2020-02-01'
# Specify target of prediction. It can be one of the following keywords:
# ER: External Refinance, PR: Property-Sale, ERPS: Mixed External-Refinance and Property-Sale,
# NP: Natural Pay-off
target: ERPS
# Configuration of the model used for prediction
model:
  class: CLS.SKLEARN.XGB
  n_jobs: 4
  fe.enabled: yes

# Specify feature names or files from which features are extracted
features:
- file_name: subset_scorer/subset_scorer_output.csv
  operations: 
  - fun: filter
    arguments: ["target == 'ERPS'", "horizon == 3"] 
  - fun: mutate
    arguments: "score = gini*importance"
  - fun: group_by
    arguments: fname
  - fun: summarise
    arguments: "score_agg = max(score, na.rm = T)"
  - fun: ungroup
  - fun: arrange
    arguments: "desc(score_agg)"
  - fun: head
    arguments: 100
  - fun: pull
    arguments: fname
- file_name: D:/Users/user.name/Documents/data/reports/subset_scorer/subset_scorer_aggregated.csv
  operations: 
  - fun: filter
    arguments: ["target == 'ERPS'", "horizon == 3"] 
  - fun: mutate
    arguments: "score = lift2p*importance"
  - fun: group_by
    arguments: fname
  - fun: summarise
    arguments: "score_agg = med(score, na.rm = T)"
  - fun: ungroup
  - fun: arrange
    arguments: "desc(score_agg)"
  - fun: head
    arguments: 50
  - fun: pull
    arguments: fname
- file_name: D:/Users/user.name/Documents/data/reports/subset_scorer/subset_scorer_aggregated.csv
  operations: 
  - fun: filter
    arguments: ["target == 'ERPS'", "horizon == 3"] 
  - fun: mutate
    arguments: "score = gini*importance"
  - fun: group_by
    arguments: fname
  - fun: summarise
    arguments: "score_agg = med(score, na.rm = T)"
  - fun: ungroup
  - fun: arrange
    arguments: "desc(score_agg)"
  - fun: head
    arguments: 50
  - fun: pull
    arguments: fname
- file_name: D:/Users/user.name/Documents/data/reports/subset_scorer/feature_correlations.csv
  operations: 
  - fun: arrange
    arguments: "desc(gini)"
  - fun: head
    arguments: 50
  - fun: pull
    arguments: fname
- file_name: D:/Users/user.name/Documents/data/reports/feature_correlations/feature_correlations.csv
  operations: 
  - fun: arrange
    arguments: "logloss"
  - fun: head
    arguments: 20
  - fun: pull
    arguments: fname
