
## Rscript R_Pipeline/modules/prediction.R skxgb1_fs1.yml

## skxgb2_fs1
dates: ['2020-01-01', '2020-02-01']
target: ERPS
# Hyperparameters are taken from ElPyPipe current_xgb for BF
model:
  class: CLS.SKLEARN.XGB
  name: skxgb2_fs1
  n_jobs: 4
  fe.enabled: yes
  colsample_bytree: 0.6
  eta: 0.05
  max_depth: 6
  min_child_weight: 75
  n_estimators: 150
  scale_pos_weight: 2
  subsample: 0.6

# fs1: feature set 1: Specify feature names
features:
  - feature_1
  - feature_2
  - feature_3
  - feature_4