---
title: "GSS Analysis"
author: "Nima Ramezani"
date: "29/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('../../..')
source('R_Pipeline/initialize.R')
base_path = sprintf("%s/%s", mc$path_reports, id_ml)

config_filename = 'gss_analysis.yml'
args = commandArgs(trailingOnly = T)
if(!is.empty(args)){
  config_filename = args[1]
}
"R_Pipeline/vignettes/gss_analysis" %>% paste(config_filename, sep = '/') %>% yaml::read_yaml() -> config

if(is.null(config$input_scores$filename)){
  sprintf("%s/prediction/%s/%s/raw_scores.csv", 
          mc$path_data, 
          config$input_agent_runid %>% substr(1,8),
          config$input_model_runid %>% substr(1,8)) -> config$input_scores$filename
  
} else {
  reports_gss_path = sprintf("%s/%s/greedy_subset_scorer", mc$path_reports, id_ml)
  config$input_scores$filename %<>% find_file(paths = reports_gss_path)
}

config$input_scores$filename %>% bigreadr::fread2() -> scores
if(!is.null(config$input_scores$operation)){
  scores %<>% rutils::operate(config$input_scores$operation)
}

scores$test_date %<>% as.character
if(is.null(config$dates)){
  config$dates = unique(scores$test_date)
}
# model profile/model performances:
scores %>% 
  dplyr::distinct(model_id, test_date, batch_number, .keep_all = T) %>% 
  filter(test_date %in% config$dates) -> mp
```

## Performance progress in batches:


```{r performance_progress}
mp %>% 
  group_by(batch_number) %>% 
  summarise(max_gini = max(gini_coefficient), max_lift_2pc = max(lift_2), max_precision_2pc = max(precision_2)) %>% 
  ungroup -> p1

# Plot Performance progress by batch number:
p1 %>% plotly::plot_ly(x = ~batch_number, y = ~max_gini, type = 'scatter', mode = 'lines') %>% 
  plotly::layout(title = 'GSS Gini progress')

p1 %>% plotly::plot_ly(x = ~batch_number, y = ~max_precision_2pc, type = 'scatter', mode = 'lines') %>% 
  plotly::layout(title = 'GSS Precision@2% progress')

p1 %>% plotly::plot_ly(x = ~batch_number, y = ~max_lift_2pc, type = 'scatter', mode = 'lines') %>% 
  plotly::layout(title = 'GSS Lift@2% progress')
```

## Best model of each batch for each month:
```{r best_models}
# best gini model, best precision model, best lift model:
mp %>% group_by(test_date) %>% 
  do({filter(., gini == max(gini)) %>% mutate(Title = 'Best gini')}) -> bgm
mp %>% group_by(test_date) %>% 
  do({filter(., precision_2pc == max(precision_2pc)) %>% mutate(Title = 'Best precision_2pc')}) -> bpm
mp %>% group_by(test_date) %>% 
  do({filter(., lift_2pc == max(lift_2pc)) %>% mutate(Title = 'Best lift_2pc')}) -> blm

rbind(bgm, bpm, blm) %>% knitr::kable()
```

## Feature Scores:
```{r feature_scores}
  

```