inputs: 
  - cba_sa_feb23
  - cba_cc_feb23

categories: script/coster/configs/universal_3.yml

from: 2022-12-01
until: 2023-03-01

# excluded_categories: ['Expenses', 'Miscellaneous', 'CreditCard', 'Proximity']

excluded_categories: ['Saving', 'Miscellaneous', 'CreditCard', 'Proximity', 'Income', 'Expenses']

output:
  transactions: sa_transactions_feb23
  buckets: sa_buckets_feb23
  
  


