inputs: 
  - cba_sa_nov22
  - cba_cc_nov22

categories: script/coster/configs/universal_2.yml

from: 2022-11-01
until: 2022-11-30

# excluded_categories: ['Expenses', 'Miscellaneous', 'CreditCard', 'Proximity']

excluded_categories: ['Saving', 'Miscellaneous', 'CreditCard', 'Proximity']

output:
  transactions: sa_transactions
  buckets: sa_buckets
  
  


