inputs: 
  - cba_sa_sep23
  - cba_cc_sep23

categories: script/coster/configs/universal_4.yml

from: 2023-06-01
until: 2023-10-01

# excluded_categories: ['Expenses', 'Miscellaneous', 'CreditCard', 'Proximity']

excluded_categories: ['Saving', 'CreditCard', 'Proximity', 'Income', 'Expenses', 'HomePurchase', 'Personal', 'UnknownTransfer']

# excluded_categories: ~

output:
  transactions: sa_transactions_sep23
  buckets: sa_buckets_sep23
  
  


