inputs: 
- cba_ns_aug-dec22

categories: script/coster/configs/buckets.yml

from: 2022-08-01
until: 2023-11-01

excluded_categories: ['Expenses', 'Miscellaneous', 'CreditCard', 'Proximity', 'Mortgage']

# excluded_categories: ['Saving', 'Miscellaneous', 'CreditCard', 'Proximity']

output:
  transactions: nbs_transactions
  buckets: bucket_balances
  
  


