inputs: 
- cba_nbs

categories: script/coster/configs/buckets.yml

from: 2022-08-01
until: 2023-02-01

excluded_categories: ['Expenses', 'Miscellaneous', 'CreditCard', 'Proximity', 'Mortgage']

# excluded_categories: ['Saving', 'Miscellaneous', 'CreditCard', 'Proximity']

output:
  transactions: nbs_transactions
  buckets: bucket_balances_feb23
  



