# ss_config_02: Same as ss_config_01 with the following differences:
## Models are trained on 80,0000 rows randomly picked from entire training dataset.

dates: ['2019-03-01', '2019-04-01', '2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01', '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01', '2020-01-01', '2020-02-01'] 
target: ERPS
horizon: 3
subset_size: 120
num_experiments: 500
model:
  class: CLS.SKLEARN.XGB
  n_jobs: 4
  colsample_bytree: 0.6
  eta: 0.05
  max_depth: 4
  min_child_weight: 75
  n_estimators: 50
  scale_pos_weight: 2
  subsample: 0.6
  smp.enabled: yes
  smp.num_rows: 80000

exclude_columns: ['label', 'label_6m','tte', 'censored', 'y_externalRefinance', 'y_propertySale', 'y_naturalPayout', 'y_loanClosed', 'uncensored_externalRefinance', 'uncensored_propertySale', 'uncensored_naturalPayout', 'originalApplicationStatus']

metrics: 
  - gini
  - lift
  - precision
  - f1
  
quantiles: 0.02

saving_period: 100    
output: 'ssc2_out'
