verbose: 1
response: churn
data:
  source: "3://event_prediction_platform.dummy.el.ai/dummyDataset.csv"
  tmp: "s3://event_prediction_platform.dummy.el.ai/run=XYZ/"
categorical:
- investmentProperty
- education
- mobileOrLandline
- gender
- dependents
- hasCreditCard
- firstHomeBuyer
- externalRefinance
- originationChannel
- pri_contact_meth
- paperless
- hasPersonalLoanAccount
storage:
  report: "s3://event_prediction_platform.dummy.el.ai/reports/"
  model: "s3://event_prediction_platform.dummy.el.ai/modelstorage/"
split: 0.5
evaluationmetric: f1
models:
- model: "Logistic Regression"
  class: "ClassificationModels.logistic_regression.LogisticRegression"
  task: "prediction-linear-regression"
- model: "XG Boost Classifier"
  class: "ClassificationModels.xgboost.XGBoostClassify"
  task: "prediction-linear-regression"
- model: "Neural Net"
  class: "ClassificationModels.neural_net.NeuralNet"
  task: "prediction-linear-regression"
compute:
  cluster: event_prediction_platform
  subnet: subnet-00bd73a8441685ba5
  securitygroup: sg-0bd52dca744ae20e4