# This is a sample config for BS Modal Example dashboard:

main:
  type: sidebarLayout
  layout.side:
    - bins
    - tabBut
  layout.main:
    - distPlot
    - modalExample
bins:
  type: sliderInput
  title: 'Number of bins:'
  min: 1
  max: 50
  value: 30
tabBut:
  type: actionButton
  title: 'View Table'
distPlot:
  type: plotOutput
  service: "get.plot(input$bins)"
modalExample:
  type: bsModal
  title: 'Data Table'
  trigger: tabBut
  size: large
  layout: distTable
distTable:
  type: dataTableOutput
  service: 'get.dt(input$bins)'
  options:
    pageLength: 10
    width: '100%'

