## Rscript R_Pipeline/modules/prediction.R agg_ssc4v6_T30tmp2.yml

# Aggregated (mean which is default) of 30 xgboost models of template SKXGB05_70PC from template set tc_01.yml where features are chosen from ss_config_04 by v6 protocole
dates: ['2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01', '2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01', '2020-05-01', '2020-06-01', '2020-07-01', '2020-08-01'] 
target: ERPS
model:
  class: ENS.RML.AGGR
  name: agg_ssc4v6_T30tmp2
  transformers:
  - class: ModelTemplate
    template_name: SKXGB05_70PC
    # T10tmp1SKXGB02_20PC
    models_name: TMP1SKXGB05_70PC
    #T30: take 30 transformers from template
    num_models: 30
    # tmp2 
    template_config: 'path/to/templates/tc_01.yml'
    features: 
      # ssc2: Specify file containing feature names and scores
      file_name: subset_scorer/ssc4_out.csv
      # protocole v6: eliminate features that have zero importance in all their experiments and keep the rest
      operations: 
        - fun: group_by
          arguments: fname
        - fun: summarise
          arguments: "importance = max(importance, na.rm = T)"
        - fun: ungroup
        - fun: filter
          arguments: "importance > 0"
        - fun: pull
          arguments: fname
