dates: '2020-02-01'
target: ERPS

model:
  class: SavedModel
  path: D:/Users/firstname.surname/Documents/data/models/xxxxxxxx/ERPS/H3/2019-08-01
  name: XGB45678
  reset: no

features:
 - feature1
 - feature2
 - file_name: subset_scorer/subset_scorer_output.csv
  operations: 
  - fun: filter
    arguments: ["target == 'ERPS'", "horizon == 3"] 
  - fun: mutate
    arguments: "score = lift2p*importance"
  - fun: group_by
    arguments: fname
  - fun: summarise
    arguments: "score_agg = med(score, na.rm = T)"
  - fun: ungroup
  - fun: arrange
    arguments: "desc(score_agg)"
  - fun: head
    arguments: 500
  - fun: pull
    arguments: fname
