## Rscript R_Pipeline/modules/prediction.R skknn1_Tpylmnn1v2.yml

# knn using a pylmnn model as transformer which in turn has a saved model as transformer

dates: ['2019-03-01', '2019-04-01', '2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01', '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01', '2020-01-01', '2020-02-01'] 
target: ERPS
add_train_performance: no
model:
  # skknn:
  class: CLS.SKLEARN.KNN
  name: skknn1_Tpylmnn1v2
  # skknn1:
  n_neighbors: 10000
  # Tpylmnn1:
  transformers:
  - class: MAP.PYLMNN.LMNN
    name: lmnn
    num_components: 20
    num_neighbors: 1000
    smp.enabled: yes
    smp.method: downsample
    smp.class_ratio: 0.5
    # v2:
    transformers:
    - class: SavedModelTransformers
      name: aggr_gssc2v1_T20tmp1SKXGB01_15PC
      reset: no
      return: logit
