# skxgb_ssc2v1_elpbf: Same as skxgb_ssc1v1_elpbf with the following differences:

dates: ['2019-03-01', '2019-04-01', '2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01', '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01', '2020-01-01', '2020-02-01'] 
target: ERPS
model:
  name: skxgb_ssc2v1_elpbf
  class: CLS.SKLEARN.XGB
  n_jobs: 4
  fe.enabled: yes
  # Hyper parameters from ElPyPipe config current_xgb for BF
  colsample_bytree: 0.6
  eta: 0.05
  max_depth: 6
  min_child_weight: 75
  n_estimators: 150
  scale_pos_weight: 2
  subsample: 0.6
  
features:
  # Uses output of subset scorer run by ss_config_02
- file_name: 'ssc2_out.csv'
  operations: 
  - fun: filter
    arguments: ["target == 'ERPS'", "horizon == 3"] 
  - fun: mutate
    arguments: "score = gini*importance"
  - fun: group_by
    arguments: fname
  - fun: summarise
    arguments: "score_agg = max(score, na.rm = T)"
  - fun: ungroup
  - fun: arrange
    arguments: "desc(score_agg)"
  - fun: head
    arguments: 500
  - fun: pull
    arguments: fname
