## Rscript R_Pipeline/modules/prediction.R skxgb2_ssc2v2.yml

dates: ['2019-03-01', '2019-04-01', '2019-05-01', '2019-06-01', '2019-07-01', '2019-08-01', '2019-09-01', '2019-10-01', '2019-11-01', '2019-12-01', '2020-01-01', '2020-02-01'] 
target: ERPS
model:
  name: skxgb2_ssc2v2
  class: CLS.SKLEARN.XGB
  n_jobs: 4
  fe.enabled: yes
  colsample_bytree: 0.6
  eta: 0.05
  max_depth: 6
  min_child_weight: 75
  n_estimators: 150
  scale_pos_weight: 2
  subsample: 0.6
  
features:
- file_name: 'subset_scorer/ss2_out.csv'
  # v2: max lift_2pc: scores are computed by multiplying lift_2pc by importance and aggregated by max.
  
  operations: 
  - fun: filter
    arguments: ["target == 'ERPS'", "horizon == 3"] 
  - fun: mutate
    arguments: "score = lift_2pc*importance"
  - fun: group_by
    arguments: fname
  - fun: summarise
    arguments: "score_agg = max(score, na.rm = T)"
  - fun: ungroup
  - fun: arrange
    arguments: "desc(score_agg)"
  - fun: head
    arguments: 500
  - fun: pull
    arguments: fname
